export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET';

export const CATEGORY_GET_REQUEST = 'CATEGORY_GET_REQUEST';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_FAIL = 'CATEGORY_GET_FAIL';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';

export const SUBCATEGORY_CREATE_REQUEST = 'SUBCATEGORY_CREATE_REQUEST';
export const SUBCATEGORY_CREATE_SUCCESS = 'SUBCATEGORY_CREATE_SUCCESS';
export const SUBCATEGORY_CREATE_FAIL = 'SUBCATEGORY_CREATE_FAIL';
export const SUBCATEGORY_CREATE_RESET = 'SUBCATEGORY_CREATE_RESET';

export const SUBCATEGORY_GET_REQUEST = 'SUBCATEGORY_GET_REQUEST';
export const SUBCATEGORY_GET_SUCCESS = 'SUBCATEGORY_GET_SUCCESS';
export const SUBCATEGORY_GET_FAIL = 'SUBCATEGORY_GET_FAIL';

export const SUBCATEGORY_UPDATE_REQUEST = 'SUBCATEGORY_UPDATE_REQUEST';
export const SUBCATEGORY_UPDATE_SUCCESS = 'SUBCATEGORY_UPDATE_SUCCESS';
export const SUBCATEGORY_UPDATE_FAIL = 'SUBCATEGORY_UPDATE_FAIL';

export const SUBCATEGORY_DELETE_REQUEST = 'SUBCATEGORY_DELETE_REQUEST';
export const SUBCATEGORY_DELETE_SUCCESS = 'SUBCATEGORY_DELETE_SUCCESS';
export const SUBCATEGORY_DELETE_FAIL = 'SUBCATEGORY_DELETE_FAIL';

